// Defines the "target server", which is the server
// that we're going to run support for. In this case, it's "the-hub"
var target = "the-hub";

// Defines how much money a server should have before we leave it alone
// In this case, it is set to 80% of the server's max money
var moneyThresh = getServerMaxMoney(target) * 0.8;

// Defines the maximum security level the target server can
// have. If the target's security level is higher than this,
// we'll weaken it before doing anything else
var securityThresh = getServerMinSecurityLevel(target) + 5;

// Infinite loop that continously grows/weakens the target server
while (true) {
	if (getServerSecurityLevel(target) > securityThresh) {
		// If the server's security level is above our threshold, weaken it
		weaken(target);
	} else if (getServerMoneyAvailable(target) < moneyThresh) {
		// If the server's money is less than our threshold, grow it
		grow(target);
	} else {
		// Otherwise, log that target is ready to hack.
		print(target, " is ripe!");
	}
}
